# Параметры релиза
release:
  name: open-webui
  namespace: prod

# Основные настройки приложения
image:
  repository: ghcr.io/open-webui/open-webui
  tag: latest
  pullPolicy: IfNotPresent

# Настройки развертывания
deployment:
  replicas: 1
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"

# Секреты
secrets:
  openai:
    apiKey: ""
    apiBase: ""
  ollama:
    apiBase: "http://ollama.prod.svc.cluster.local:11434/api"
  custom: {}

# Настройки окружения (не секретные)
env:
  - name: MODEL
    value: "deepseek-r1:14b"
  - name: OLLAMA_API_BASE
    value: "http://ollama.prod.svc.cluster.local:11434/api"
  - name: DEBUG
    value: "false"
  - name: ENABLE_MEMORY_REDUCTION
    value: "true"
  - name: COMPUTE_SHAPES
    value: "false"
  - name: MAX_PARALLEL_REQUESTS
    value: "2"
  - name: NODE_OPTIONS
    value: "--max-old-space-size=3072"
  - name: MODEL_CONTEXT_WINDOW
    value: "4096"
  - name: BATCH_SIZE
    value: "4"
  - name: MAX_TOKENS
    value: "2048"
  - name: TEMPERATURE
    value: "0.7"
  - name: TOP_P
    value: "0.9"
  - name: ENABLE_RESPONSE_STREAMING
    value: "true"
  - name: ENABLE_AGGRESSIVE_GC
    value: "true"

# Настройки сервиса
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}
  labels: {}

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: webui.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: open-webui-tls
      hosts:
        - webui.prod.local


persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
