# Параметры релиза
release:
  name: open-webui
  namespace: prod

# Основные настройки приложения
image:
  repository: ghcr.io/open-webui/open-webui
  tag: latest
  pullPolicy: Always

# Настройки развертывания
deployment:
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Секреты
secrets:
  openai:
    apiKey: ""
    apiBase: "https://api.openai.com/v1"
  ollama:
    apiBase: "http://ollama.prod.svc.cluster.local:11434/api"
  custom: {}

# Настройки окружения (не секретные)
env:
  - name: MODEL
    value: "gpt-3.5-turbo"
  - name: DEBUG
    value: "true"

# Настройки сервиса
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: open-webui.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: open-webui-tls
      hosts:
        - open-webui.local

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
