# Параметры релиза
release:
  name: open-webui
  namespace: prod

# Основные настройки приложения
image:
  repository: ghcr.io/open-webui/open-webui
  tag: latest
  pullPolicy: Always

# Настройки развертывания
deployment:
  replicas: 1
  resources:
    limits:
      cpu: 400m        # Дополнительно уменьшено для оптимизации
      memory: 768Mi    # Оптимизировано под текущие настройки
    requests:
      cpu: 200m        # Уменьшено для более эффективного использования
      memory: 384Mi    # Оптимизировано под включенную память

# Секреты
secrets:
  openai:
    apiKey: ""
    apiBase: ""
  ollama:
    apiBase: "http://ollama.prod.svc.cluster.local:11434/api"
  custom: {}

# Настройки окружения (не секретные)
env:
  - name: MODEL
    value: "llama2"
  - name: DEBUG
    value: "false"  # Отключаем отладку для уменьшения потребления памяти
  - name: OLLAMA_MODEL
    value: "llama2"
  - name: DEFAULT_MODEL
    value: "llama2"
  - name: ENABLE_MEMORY_REDUCTION
    value: "true"   # Включаем оптимизацию памяти
  - name: COMPUTE_SHAPES
    value: "false"  # Отключаем вычисление форм для экономии памяти
  - name: CUDA_LAUNCH_BLOCKING
    value: "1"      # Улучшаем управление памятью GPU
  - name: MAX_PARALLEL_REQUESTS
    value: "2"      # Уменьшаем количество параллельных запросов для экономии памяти
  - name: ENABLE_AGGRESSIVE_GC
    value: "true"   # Включаем агрессивный сборщик мусора
  - name: NODE_OPTIONS
    value: "--max-old-space-size=384"  # Ограничиваем использование памяти Node.js


# Настройки сервиса
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}
  labels: {}

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: webui.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: open-webui-tls
      hosts:
        - webui.prod.local


persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
