# Параметры релиза
release:
  name: open-webui
  namespace: prod

# Основные настройки приложения
image:
  repository: ghcr.io/open-webui/open-webui
  tag: latest
  pullPolicy: Always

# Настройки развертывания
deployment:
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Секреты
secrets:
  openai:
    apiKey: ""
    apiBase: ""
  ollama:
    apiBase: "http://ollama.prod.svc.cluster.local:11434/api"
  custom: {}

# Настройки окружения (не секретные)
env:
  - name: MODEL
    value: "llama2"
  - name: DEBUG
    value: "true"
  - name: OLLAMA_MODEL
    value: "llama2"
  - name: DEFAULT_MODEL
    value: "llama2"

# Настройки сервиса
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}
  labels: {}

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: webui.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: open-webui-tls
      hosts:
        - webui.prod.local


persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
