apiVersion: v2
name: sidecar-injector
description: "Helm chart for TLS sidecar injection with automatic certificate management"
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - tls
  - sidecar
  - security
  - proxy
maintainers:
  - name: "DevSecMLOps"
    email: "i8megabit@gmail.com"
dependencies:
  - name: cert-manager
    version: ">=1.0.0"
    repository: "https://charts.jetstack.io"
    condition: certManager.enabled
