# Copyright (c) 2023-2025 Mikhail Eberil (@eberil)
# 
# This file is part of Ƶakenak™® project.
# https://github.com/i8megabit/zakenak
#
# This program is free software and is released under the terms of the MIT License.
# See LICENSE.md file in the project root for full license information.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#
# TRADEMARK NOTICE:
# Ƶakenak™® and the Ƶakenak logo are registered trademarks of Mikhail Eberil.
# All rights reserved. The Ƶakenak trademark and brand may not be used in any way 
# without express written permission from the trademark owner.


apiVersion: v2
name: sidecar-injector
description: "Helm chart for TLS sidecar injection with automatic certificate management"
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - tls
  - sidecar
  - security
  - proxy
maintainers:
  - name: "DevSecMLOps"
    email: "i8megabit@gmail.com"
dependencies:
  - name: cert-manager
    version: ">=1.0.0"
    repository: "https://charts.jetstack.io"
    condition: certManager.enabled
