# Параметры релиза
release:
  name: sidecar-injector
  namespace: prod

nameOverride: ""
fullnameOverride: ""

# Основные настройки
image: nginx:alpine
containerPort: 8080

certManager:
  enabled: true
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

# Добавляем настройки для RBAC
rbac:
  create: true
  serviceAccount:
    create: true
    name: ""

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: sidecar-injector.local
    paths:
    - path: /
      pathType: Prefix

sidecar:
  image: nginx:alpine
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  ingressSidecar:
    enabled: true
    port: 8443
    containerPort: 8081
    volumeMounts:
    - name: tls-certs
      mountPath: /etc/tls
      readOnly: true

  egressSidecar:
    enabled: true
    port: 8444
    containerPort: 8082
    volumeMounts:
    - name: tls-certs
      mountPath: /etc/tls
      readOnly: true
