# Copyright (c) 2023-2025 Mikhail Eberil (@eberil)
# 
# This file is part of Ƶakenak™® project.
# https://github.com/i8megabit/zakenak
#
# This program is free software and is released under the terms of the MIT License.
# See LICENSE.md file in the project root for full license information.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#
# TRADEMARK NOTICE:
# Ƶakenak™® and the Ƶakenak logo are registered trademarks of Mikhail Eberil.
# All rights reserved. The Ƶakenak trademark and brand may not be used in any way 
# without express written permission from the trademark owner.


# Параметры релиза
release:
  name: sidecar-injector
  namespace: prod

nameOverride: ""
fullnameOverride: ""

volumes:
  - name: tls-certs
    secret:
      secretName: sidecar-injector-tls

# Основные настройки
image: nginx:alpine
containerPort: 8080

certManager:
  enabled: true
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

# Добавляем настройки для RBAC
rbac:
  create: true
  serviceAccount:
    create: true
    name: ""

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: sidecar-injector.prod.local
    paths:
    - path: /
      pathType: Prefix

sidecar:
  image: nginx:alpine
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi
  
  ingressSidecar:
    enabled: true
    port: 8443
    containerPort: 8443
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    config: |
      server {
          listen 8443;
          server_name localhost;
          location / {
              proxy_pass http://localhost:8080;
          }
      }
    volumeMounts:
    - name: tls-certs
      mountPath: /etc/tls
      readOnly: true
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf

  egressSidecar:
    enabled: true
    port: 8444
    containerPort: 8444
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    config: |
      server {
          listen 8444;
          server_name localhost;
          location / {
              proxy_pass http://localhost:8080;
          }
      }
    volumeMounts:
    - name: tls-certs
      mountPath: /etc/tls
      readOnly: true
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf

