{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
 acme:
  email: {{ .Values.clusterIssuer.email }}
  server: {{ .Values.clusterIssuer.server }}
  privateKeySecretRef:
    name: {{ .Values.clusterIssuer.privateKeySecretRef }}
  solvers:
  {{- toYaml .Values.clusterIssuer.solvers | nindent 2 }}
{{- end }}
