{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Values.release.namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-local-ca
  namespace: {{ .Values.release.namespace }}
spec:
  isCA: true
  commonName: "*.prod.local"
  secretName: prod-local-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - "*.prod.local"
    - "prod.local"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-local-issuer
  namespace: {{ .Values.release.namespace }}
spec:
  ca:
    secretName: prod-local-ca
{{- end }}
