apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
scheduling:
  nodeSelector:
    nvidia.com/gpu: "present"
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule