# Глобальные настройки для всех чартов
global:
 environment: production
 domain: prod.local

# Настройки cert-manager
cert-manager:
 email: "i8megabit@gmail.com"
 server: "https://acme-v02.api.letsencrypt.org/directory"

# Настройки для сайдкаров
sidecar-injector:
 certManager:
  enabled: true
  issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
 ingress:
  enabled: true
  hosts:
  - host: prod.local