# Copyright (c) 2023-2025 Mikhail Eberil (@eberil)
# 
# This file is part of Ƶakenak™® project.
# https://github.com/i8megabit/zakenak
#
# This program is free software and is released under the terms of the MIT License.
# See LICENSE.md file in the project root for full license information.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#
# TRADEMARK NOTICE:
# Ƶakenak™® and the Ƶakenak logo are registered trademarks of Mikhail Eberil.
# All rights reserved. The Ƶakenak trademark and brand may not be used in any way 
# without express written permission from the trademark owner.

# Глобальные настройки для всех чартов
global:
 environment: production
 domain: prod.local

# Настройки cert-manager
cert-manager:
 email: "i8megabit@gmail.com"
 server: "https://acme-v02.api.letsencrypt.org/directory"

# Настройки для сайдкаров
sidecar-injector:
 certManager:
  enabled: true
  issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
 ingress:
  enabled: true
  hosts:
  - host: prod.local