# Параметры релиза
release:
  name: ollama
  namespace: prod

# Основные настройки приложения
image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

# Настройки развертывания
deployment:
  replicas: 1
  resources:
    limits:
      cpu: "4"
      memory: "16Gi"
    requests:
      cpu: "2"
      memory: "8Gi"
  env:
    - name: OLLAMA_MODELS
      value: "deepseek-r1:14b"
    - name: OLLAMA_HOST
      value: "0.0.0.0"
    - name: OLLAMA_COMPUTE_TYPE
      value: "cuda"
    - name: OLLAMA_CUDA_DEVICE
      value: "0"
    - name: OLLAMA_BATCH_SIZE
      value: "8"
    - name: OLLAMA_PARALLEL_REQUESTS
      value: "2"
    - name: OLLAMA_THREAD_COUNT
      value: "8"
    - name: OLLAMA_GPU_LAYERS
      value: "all"
    - name: OLLAMA_F16
      value: "true"
    - name: OLLAMA_TENSOR_PARALLEL
      value: "true"
    - name: OLLAMA_GPU_MEMORY_UTILIZATION
      value: "0.95"
    - name: OLLAMA_FLASH_ATTENTION
      value: "true"
    - name: OLLAMA_KV_CACHE_STRATEGY
      value: "dynamic"
    - name: OLLAMA_CUDA_GRAPHS
      value: "true"


# Настройки сервиса
service:
  type: ClusterIP
  port: 11434
  targetPort: 11434

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: ollama.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ollama-tls
      hosts:
        - ollama.prod.local


# Настройки хранилища для моделей
persistence:
  enabled: true
  size: 50Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Настройки безопасности
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Настройки сети
networkPolicy:
  enabled: true
  allowedNamespaces:
    - prod
