# Параметры релиза
release:
  name: ollama
  namespace: prod

# Основные настройки приложения
image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

# Настройки развертывания
deployment:
  replicas: 1
  resources:
    limits:
      cpu: "16"
      memory: "32Gi"
      nvidia.com/gpu: "1"
    requests:
      cpu: "8"
      memory: "16Gi"
  env:
    - name: OLLAMA_MODELS
      value: "deepseek-r1:14b"
    - name: OLLAMA_HOST
      value: "0.0.0.0"
    - name: OLLAMA_COMPUTE_TYPE
      value: "cuda"
    - name: OLLAMA_BATCH_SIZE
      value: "8"
    - name: OLLAMA_PARALLEL_REQUESTS
      value: "2"
    - name: OLLAMA_GRAMMAR_CACHE
      value: "true"
    - name: OLLAMA_GRAMMAR_CACHE_SIZE
      value: "1024"
    - name: OLLAMA_REQUEST_TIMEOUT
      value: "300"
    - name: OLLAMA_ENABLE_OPTIMIZATION
      value: "true"
    - name: OLLAMA_MEMORY_UTILIZATION
      value: "high"
    - name: OLLAMA_THREAD_COUNT
      value: "8"
    - name: OLLAMA_CONTEXT_WINDOW
      value: "4096"
    - name: OLLAMA_MAX_TOKENS
      value: "2048"
    - name: OLLAMA_ENABLE_GRAMMAR_CHECK
      value: "true"
    - name: OLLAMA_ENABLE_REQUEST_OPTIMIZATION
      value: "true"
    - name: OLLAMA_MODEL_SPECIFIC_OPTS
      value: "deepseek-r1:14b=high_performance"

# Настройки сервиса
service:
  type: ClusterIP
  port: 11434
  targetPort: 11434

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: ollama.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ollama-tls
      hosts:
        - ollama.prod.local


# Настройки хранилища для моделей
persistence:
  enabled: true
  size: 50Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Настройки безопасности
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Настройки сети
networkPolicy:
  enabled: true
  allowedNamespaces:
    - prod
