# Copyright (c) 2023-2025 Mikhail Eberil (@eberil)
# 
# This file is part of Ƶakenak™® project.
# https://github.com/i8megabit/zakenak
#
# This program is free software and is released under the terms of the MIT License.
# See LICENSE.md file in the project root for full license information.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#
# TRADEMARK NOTICE:
# Ƶakenak™® and the Ƶakenak logo are registered trademarks of Mikhail Eberil.
# All rights reserved. The Ƶakenak trademark and brand may not be used in any way 
# without express written permission from the trademark owner.

# Параметры релиза
release:
  name: ollama
  namespace: prod

# Основные настройки приложения
image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

# Настройки развертывания
deployment:
  replicas: 1
  useGPU: true  # Флаг для включения/отключения GPU
  resources:
    limits:
      cpu: "8"
      memory: "16Gi"
      nvidia.com/gpu: "1"
    requests:
      cpu: "4"
      memory: "8Gi"
  env:
    - name: OLLAMA_MODELS
      value: "deepseek-r1:14b"
    - name: OLLAMA_HOST
      value: "0.0.0.0"
    - name: OLLAMA_COMPUTE_TYPE
      value: "gpu"
    - name: OLLAMA_BATCH_SIZE
      value: "8"
    - name: OLLAMA_PARALLEL_REQUESTS
      value: "2"
    - name: OLLAMA_THREAD_COUNT
      value: "4"
    - name: OLLAMA_GPU_LAYERS
      value: "43"
    - name: OLLAMA_F16
      value: "true"
    - name: OLLAMA_TENSOR_PARALLEL
      value: "true"
    - name: OLLAMA_GPU_MEMORY_UTILIZATION
      value: "0.75"
    - name: OLLAMA_FLASH_ATTENTION
      value: "true"
    - name: OLLAMA_KV_CACHE_STRATEGY
      value: "dynamic"





# Настройки сервиса
service:
  type: ClusterIP
  port: 11434
  targetPort: 11434

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: ollama.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ollama-tls
      hosts:
        - ollama.prod.local


# Настройки хранилища для моделей
persistence:
  enabled: true
  size: 50Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Настройки безопасности
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Настройки сети
networkPolicy:
  enabled: true
  allowedNamespaces:
    - prod
