# Параметры релиза
release:
  name: ollama
  namespace: prod

# Основные настройки приложения
image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

# Настройки развертывания
deployment:
  replicas: 1
  useGPU: false  # Флаг для включения/отключения GPU
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
    requests:
      cpu: "2"
      memory: "4Gi"
  env:
    - name: OLLAMA_MODELS
      value: "deepseek-r1:14b"
    - name: OLLAMA_HOST
      value: "0.0.0.0"
    - name: OLLAMA_COMPUTE_TYPE
      value: "cpu"  # По умолчанию используем CPU
    - name: OLLAMA_BATCH_SIZE
      value: "4"
    - name: OLLAMA_PARALLEL_REQUESTS
      value: "2"
    - name: OLLAMA_THREAD_COUNT
      value: "4"
    - name: OLLAMA_CONTEXT_WINDOW
      value: "4096"
    - name: OLLAMA_MAX_TOKENS
      value: "2048"
    - name: OLLAMA_ENABLE_MEMORY_REDUCTION
      value: "true"
    - name: OLLAMA_ENABLE_AGGRESSIVE_GC
      value: "true"




# Настройки сервиса
service:
  type: ClusterIP
  port: 11434
  targetPort: 11434

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: ollama.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ollama-tls
      hosts:
        - ollama.prod.local


# Настройки хранилища для моделей
persistence:
  enabled: true
  size: 50Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Настройки безопасности
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Настройки сети
networkPolicy:
  enabled: true
  allowedNamespaces:
    - prod
