{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
	name: {{ include "sidecar-injector.fullname" . }}-cert
spec:
	secretName: {{ include "sidecar-injector.fullname" . }}-tls
	duration: 2160h # 90d
	renewBefore: 360h # 15d
	subject:
		organizations:
		- 'JSC "EBERIL INK"'
	commonName: {{ index .Values.ingress.hosts 0 "host" }}
	dnsNames:
	{{- range .Values.ingress.hosts }}
	- {{ .host }}
	{{- end }}
	issuerRef:
		name: {{ .Values.certManager.issuerRef.name }}
		kind: {{ .Values.certManager.issuerRef.kind }}
{{- end }}