apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sidecar-injector.fullname" . }}-nginx-config
  namespace: {{ .Values.release.namespace }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
data:
  nginx-ingress.conf: |
    server {
        listen {{ .Values.sidecar.ingressSidecar.containerPort }};
        server_name localhost;
        location / {
            proxy_pass http://localhost:{{ .Values.containerPort }};
        }
    }
  nginx-egress.conf: |
    server {
        listen {{ .Values.sidecar.egressSidecar.containerPort }};
        server_name localhost;
        location / {
            proxy_pass http://localhost:{{ .Values.containerPort }};
        }
    }
