apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ include "sidecar-injector.fullname" . }}
spec:
 replicas: 1
 selector:
  matchLabels:
   {{- include "sidecar-injector.selectorLabels" . | nindent 4 }}
 template:
  metadata:
   labels:
    {{- include "sidecar-injector.selectorLabels" . | nindent 4 }}
  spec:
   volumes:
   - name: tls-certs
     secret:
      secretName: {{ include "sidecar-injector.fullname" . }}-tls
   containers:
   - name: main
     image: {{ .Values.image }}
     ports:
     - containerPort: {{ .Values.containerPort }}
     resources:
     {{- toYaml .Values.resources | nindent 6 }}
   {{- if .Values.sidecar.ingressSidecar.enabled }}
   - name: ingress-sidecar
     image: {{ .Values.sidecar.image }}
     ports:
     - containerPort: {{ .Values.sidecar.ingressSidecar.containerPort }}
     volumeMounts:
     {{- toYaml .Values.sidecar.ingressSidecar.volumeMounts | nindent 6 }}
   {{- end }}
   {{- if .Values.sidecar.egressSidecar.enabled }}
   - name: egress-sidecar
     image: {{ .Values.sidecar.image }}
     ports:
     - containerPort: {{ .Values.sidecar.egressSidecar.containerPort }}
     volumeMounts:
     {{- toYaml .Values.sidecar.egressSidecar.volumeMounts | nindent 6 }}
   {{- end }}

