apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
	name: selfsigned-issuer
	namespace: {{ .Values.release.namespace }}
spec:
	selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
	name: root-ca
	namespace: {{ .Values.release.namespace }}
spec:
	isCA: true
	commonName: {{ .Values.ca.commonName }}
	secretName: root-ca-key-pair
	duration: {{ .Values.ca.validityDuration }}
	renewBefore: {{ .Values.ca.renewBefore }}
	subject:
		organizations:
			- {{ .Values.ca.organization }}
	privateKey:
		algorithm: ECDSA
		size: 256
	issuerRef:
		name: selfsigned-issuer
		kind: ClusterIssuer
		group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
	name: local-ca-issuer
	namespace: {{ .Values.release.namespace }}
spec:
	ca:
		secretName: root-ca-key-pair