apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.release.namespace }}
  labels:
    app: ollama
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      {{- if .Values.deployment.useGPU }}
      nodeSelector:
        nvidia.com/gpu: "present"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      {{- end }}
      containers:
        - name: ollama
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOME
              value: /data
            {{- if .Values.deployment.useGPU }}
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: CUDA_VISIBLE_DEVICES
              value: "all"
            - name: OLLAMA_COMPUTE_TYPE
              value: "cuda"
            {{- end }}
            {{- with .Values.deployment.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            resources:
            {{- if .Values.deployment.useGPU }}
            {{- toYaml .Values.deployment.resources.gpu | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.deployment.resources.cpu | nindent 12 }}
            {{- end }}

          volumeMounts:
            - name: ollama-data
              mountPath: /data
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc



