apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.release.namespace }}
  labels:
    app: ollama
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        nvidia.com/gpu: "present"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      initContainers:
        - name: init-ollama-dir
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /data/.ollama && \
              chown -R 1000:1000 /data/.ollama && \
              chmod -R 755 /data/.ollama
          volumeMounts:
            - name: ollama-data
              mountPath: /data
      containers:
        - name: ollama
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOME
              value: /data
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: CUDA_VISIBLE_DEVICES
              value: "all"
            {{- with .Values.deployment.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.deployment.resources.limits.gpu | default "1" }}
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: ollama-data
              mountPath: /data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      {{- end }}
