apiVersion: apps/v1
kind: Deployment
metadata:
	name: {{ .Release.Name }}
	namespace: {{ .Values.release.namespace }}
	labels:
		app: ollama
spec:
	replicas: {{ .Values.deployment.replicas }}
	selector:
		matchLabels:
			app: ollama
	template:
		metadata:
			labels:
				app: ollama
		spec:
			securityContext:
				{{- toYaml .Values.securityContext | nindent 8 }}
			containers:
				- name: ollama
					image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
					imagePullPolicy: {{ .Values.image.pullPolicy }}
					ports:
						- containerPort: {{ .Values.service.targetPort }}
							protocol: TCP
					resources:
						{{- toYaml .Values.deployment.resources | nindent 12 }}
					{{- if .Values.persistence.enabled }}
					volumeMounts:
						- name: ollama-data
							mountPath: /root/.ollama
					{{- end }}
			{{- if .Values.persistence.enabled }}
			volumes:
				- name: ollama-data
					persistentVolumeClaim:
						claimName: {{ .Release.Name }}-pvc
			{{- end }}