apiVersion: v1
kind: Node
metadata:
	name: kind-control-plane  # Имя ноды в kind-кластере
	labels:
		accelerator: nvidia-gpu
		nvidia.com/cuda.capable: "true"
		nvidia.com/cuda.runtime.major: "12"
		nvidia.com/cuda.runtime.minor: "8"
		nvidia.com/cuda.driver.major: "550"
		nvidia.com/gpu.present: "true"