apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nvidia-config
  namespace: {{ .Values.release.namespace }}
data:
  cuda-devicequery.sh: |
    #!/bin/bash
    nvidia-smi -q
    nvidia-smi --query-gpu=gpu_name,memory.total,memory.free,memory.used --format=csv,noheader
  config: |
    {
      "default-runtime": "nvidia",
      "runtimes": {
        "nvidia": {
          "path": "/usr/bin/nvidia-container-runtime",
          "runtimeArgs": []
        }
      }
    }
