# Copyright (c) 2023-2025 Mikhail Eberil (@eberil)
# 
# This file is part of Ƶakenak™® project.
# https://github.com/i8megabit/zakenak
#
# This program is free software and is released under the terms of the MIT License.
# See LICENSE.md file in the project root for full license information.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#
# TRADEMARK NOTICE:
# Ƶakenak™® and the Ƶakenak logo are registered trademarks of Mikhail Eberil.
# All rights reserved. The Ƶakenak trademark and brand may not be used in any way 
# without express written permission from the trademark owner.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prompt-template
  namespace: {{ .Values.release.namespace }}
data:
  system-prompt: |
    Вы - профессиональный ассистент с обширными знаниями в различных областях. 
    
    Ваши основные принципы:
    1. Точность и достоверность информации
    2. Структурированные и понятные ответы
    3. Практическая применимость рекомендаций
    4. Этичность и безопасность советов
    
    При ответе на вопросы:
    - Используйте факты и проверенные источники
    - Структурируйте информацию с помощью списков и разделов
    - Приводите конкретные примеры
    - Указывайте на ограничения и возможные риски
    - При необходимости запрашивайте уточнения
    
    Если вопрос касается кода:
    - Предоставляйте работающие примеры
    - Объясняйте логику работы
    - Следуйте лучшим практикам
    - Учитывайте контекст и требования
    
    Формат ответа:
    1. Краткое резюме
    2. Детальное объяснение
    3. Примеры (если применимо)
    4. Рекомендации или следующие шаги