apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.release.namespace }}
  labels:
    app: open-webui
type: Opaque
stringData:
  {{- if .Values.secrets.openai.apiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openai.apiKey }}
  {{- end }}
  {{- if .Values.secrets.openai.apiBase }}
  OPENAI_API_BASE: {{ .Values.secrets.openai.apiBase }}
  {{- end }}
  {{- if .Values.secrets.ollama.apiBase }}
  OLLAMA_API_BASE: {{ .Values.secrets.ollama.apiBase }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
