apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-security-profile
  namespace: system
data:
  nvidia-container-runtime-config: |
    {
      "default-runtime": "nvidia",
      "runtimes": {
        "nvidia": {
          "path": "/usr/bin/nvidia-container-runtime",
          "runtimeArgs": []
        }
      }
    }
  gpu-restrictions: |
    {
      "defaultContainerLimits": {
        "nvidia.com/gpu": "1"
      },
      "allowedDevices": ["all"],
      "securityContext": {
        "capabilities": {
          "drop": ["ALL"],
          "add": ["SYS_ADMIN"]
        },
        "seLinuxOptions": {
          "level": "s0"
        },
        "seccompProfile": {
          "type": "RuntimeDefault"
        }
      }
    }