name: Build Zakenak

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Initialize Go module
      run: |
        go mod init github.com/i8megabit/zakenak
        go mod tidy

    - name: Build Binary
      run: |
        mkdir -p build
        go build -o build/zakenak ./cmd/zakenak

    - name: Test Binary
      if: github.ref == 'refs/heads/develop'
      run: |
        chmod +x build/zakenak
        # Базовое тестирование версии
        ./build/zakenak --version
        # Проверка основных команд
        ./build/zakenak --help
        # Проверка конфигурации
        ./build/zakenak --config test-config.yaml || true
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: false
        tags: ghcr.io/i8megabit/zakenak:${{ github.sha }}

    - name: Run tests
      run: |
        go test ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zakenak
        path: build/zakenak
        compression-level: 9
        retention-days: 5

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/i8megabit/zakenak:${{ github.sha }}
          ghcr.io/i8megabit/zakenak:latest