name: Ƶakenak™® CI/CD

on:
	push:
		branches: [ "main", "develop" ]
		tags: [ "v*" ]
	pull_request:
		branches: [ "main", "develop" ]

env:
	REGISTRY: ghcr.io
	IMAGE_NAME: ${{ github.repository }}

jobs:
	build:
		runs-on: ubuntu-latest
		permissions:
			contents: read
			packages: write

		steps:
			- name: Checkout repository
				uses: actions/checkout@v4

			- name: Set up Go
				uses: actions/setup-go@v4
				with:
					go-version: '1.21'
					cache: true

			- name: Install dependencies
				run: |
					go mod download
					go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

			- name: Run linters
				run: golangci-lint run ./...

			- name: Run tests
				run: go test -v ./...

			- name: Build binary
				run: |
					CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
					go build -v -o zakenak \
					-ldflags "-X main.Version=${GITHUB_REF_NAME} -X main.Commit=${GITHUB_SHA} -X main.BuildDate=$(date -u +'%Y-%m-%d_%H:%M:%S')" \
					./cmd/zakenak

			- name: Log in to the Container registry
				if: github.event_name != 'pull_request'
				uses: docker/login-action@v3
				with:
					registry: ${{ env.REGISTRY }}
					username: ${{ github.actor }}
					password: ${{ secrets.GITHUB_TOKEN }}

			- name: Build and push Docker image
				if: github.event_name != 'pull_request'
				uses: docker/build-push-action@v5
				with:
					context: .
					push: true
					tags: |
						${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
						${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
					build-args: |
						VERSION=${{ github.ref_name }}
						COMMIT=${{ github.sha }}
						BUILD_DATE=$(date -u +'%Y-%m-%d_%H:%M:%S')

			- name: Create Release
				if: startsWith(github.ref, 'refs/tags/v')
				uses: softprops/action-gh-release@v1
				with:
					files: |
						zakenak
						LICENSE
					body_path: CHANGELOG.md
					draft: false
					prerelease: false
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}