name: Build Ƶakenak™®

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
        sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
        wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda-repo-ubuntu2204-12-8-local_12.8.0-1_amd64.deb
        sudo dpkg -i cuda-repo-ubuntu2204-12-8-local_12.8.0-1_amd64.deb
        sudo cp /var/cuda-repo-ubuntu2204-12-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
        sudo apt-get update
        sudo apt-get -y install cuda

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build Binary
      run: |
        cd tools/zakenak
        make build
        
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: tools/zakenak
        file: tools/zakenak/Dockerfile
        push: false
        tags: ghcr.io/i8megabit/zakenak:${{ github.sha }}

    - name: Run tests
      run: |
        cd tools/zakenak
        make test

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zakenak
        path: tools/zakenak/build/zakenak
        compression-level: 9
        retention-days: 5

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: tools/zakenak
        file: tools/zakenak/Dockerfile
        push: true
        tags: |
          ghcr.io/i8megabit/zakenak:${{ github.sha }}
          ghcr.io/i8megabit/zakenak:latest