name: Build and Deploy Ƶakenak™®

on:
	push:
		branches: [ main, develop ]
	pull_request:
		branches: [ main, develop ]

env:
	REGISTRY: ghcr.io
	IMAGE_NAME: ${{ github.repository }}

jobs:
	build:
		runs-on: ubuntu-latest
		permissions:
			contents: read
			packages: write
			id-token: write

		steps:
		- uses: actions/checkout@v3
			with:
				token: ${{ secrets.GITHUB_TOKEN }}

		- name: Set up Go
			uses: actions/setup-go@v4
			with:
				go-version: '1.21'

		- name: Configure Git
			run: |
				git config --global user.name "GitHub Actions"
				git config --global user.email "actions@github.com"

		- name: Log in to GitHub Container Registry
			uses: docker/login-action@v3
			with:
				registry: ${{ env.REGISTRY }}
				username: ${{ github.actor }}
				password: ${{ secrets.GITHUB_TOKEN }}

		- name: Set up Docker Buildx
			uses: docker/setup-buildx-action@v3

		- name: Build and test
			env:
				GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
				PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
			run: |
				make build
				make test

		- name: Build and push Docker image
			uses: docker/build-push-action@v5
			with:
				context: .
				push: ${{ github.event_name != 'pull_request' }}
				tags: |
					${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
					${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
				cache-from: type=gha
				cache-to: type=gha,mode=max

		- name: Deploy to Kubernetes
			if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
			env:
				KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
			run: |
				echo "$KUBECONFIG_DATA" > kubeconfig.yaml
				export KUBECONFIG=kubeconfig.yaml
				make deploy
