name: Release Build

on:
  push:
    branches:
      - 'release/*'
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
		
    steps:
      - name: Checkout code
        uses: actions/checkout@v3	
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'			
      - name: Install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-8			
      - name: Build
        run: |
          export PATH=/usr/local/cuda-12.8/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:$LD_LIBRARY_PATH
          make build			
      - name: Run tests
        run: make test
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/zakenak
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}			
      - name: Upload artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v3
        with:
          name: zakenak-binary
          path: bin/zakenak