name: Release Build

on:
  push:
    branches:
      - 'release/*'
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
		
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Initialize Go module
        working-directory: .
        run: |
          go mod init github.com/i8megabit/zakenak
          go mod tidy
      - name: Build
        working-directory: .
        run: |
          mkdir -p build
          go build -o build/zakenak ./cmd/zakenak
      - name: Run tests
        run: make test
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/zakenak
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}			
      - name: Upload artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: zakenak-binary
          path: build/zakenak
          compression-level: 9
