name: Release Build

on:
  push:
    branches:
      - 'release/*'
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Initialize Go Module
        run: |
          if [ ! -f go.mod ]; then
          cd ./tools/zakenak 
          go mod init github.com/eberil/zakenak
          go mod tidy
          fi
      - name: Build
        run: |
          make build			
      - name: Run tests
        run: make test
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./tools/zakenak/bin/zakenak
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}			
      - name: Upload artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: zakenak-binary
          path: ./tools/zakenak/bin/zakenak